### ISSUE TITLE
Invalid keyword 'str' for variable 'master_type' 

### ISSUE THREAD

**Issue by StephTruong** [MIDS-scaling-up/coursework#67]
Hello 
When running the command 
' salt-cloud -p sl_centos7_small mytestvs'

I am running into this error:
`Invalid keyword 'str' for variable 'master_type'`

Anyone else having the same problem?

**Comment by nminus1** [comment]
could be a problem with you provider/profile files. can you post your cloud.providers.d,cloud.profiles.d files ?

**Comment by StephTruong** [comment]
cloud.providers.d:

sl:
 minion:
  master: 184.173.61.44
 user: SL705595
 apikey: <apikey>
 provider: softlayer
 script: bootstrap-salt
 script_args: -ZD
 delete_sshkeys: True
 display_ssh_output: False
 wait_for_ip_timeout: 1800
 ssh_connect_timeout: 1200
 wait_for_fun_timeout: 1200

cloud.profiles.d:

sl_centos7_small:
 provider: sl
 image: CENTOS_7_64
 cpu_number: 1
 ram: 1024
 disk_size: 25
 local_disk: True
 hourly_billing: True
 domain: struong.w251.com
 location: hou02

**Comment by StephTruong** [comment]
it doesnt show here but the lines have the correct indentation in my files.

**Comment by StephTruong** [comment]
i solved the problem by adding git 2015.5 on the script_args line in cloud.providers.d
